from django.contrib import admin
from .models import Company, Products, SubDistributors, OpeningStockHistory, TodayOpeningStock, TodayNewStock, NewStockHistory, TodayClosingStock, ClosingStockHistory, AccessStatus, WholesaleRecord, RetailRecord, SubRecord, ShopDeliveryRecord, ActiveDeliveryStartRecord, ActiveDeliverySalesRecord, TodayDeliveryStartRecord, TodayDeliverySalesRecord, Invoice, Profile, TotalAudit, todayTauditId, TodayInvoiceNumber, messages, TodayAudit, Remmittance, Catalogue

admin.site.register(Company)
admin.site.register(Products)
admin.site.register(SubDistributors)
admin.site.register(OpeningStockHistory)
admin.site.register(TodayOpeningStock)
admin.site.register(TodayNewStock)
admin.site.register(NewStockHistory)
admin.site.register(TodayClosingStock)
admin.site.register(ClosingStockHistory)
admin.site.register(AccessStatus)
admin.site.register(WholesaleRecord)
admin.site.register(RetailRecord)
admin.site.register(SubRecord)
admin.site.register(ShopDeliveryRecord)
admin.site.register(ActiveDeliveryStartRecord)
admin.site.register(ActiveDeliverySalesRecord)
admin.site.register(TodayDeliveryStartRecord)
admin.site.register(TodayDeliverySalesRecord)
admin.site.register(Invoice)
admin.site.register(Profile)
admin.site.register(TotalAudit)
admin.site.register(todayTauditId)
admin.site.register(TodayInvoiceNumber)
admin.site.register(messages)
admin.site.register(TodayAudit)
admin.site.register(Remmittance)
admin.site.register(Catalogue)

